services:
  postgres:
    build:
      context: postgreDB
    image: "postgres:latest"
    container_name: ${PG_CONTAINER_NAME}
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: ${PGDATA}
    volumes:
      - ./postgreDB:/var/lib/postgresql/data
    ports:
      - "5433:5433"
    restart: unless-stopped